[profile.default]
src = "src"
out = "out"
libs = ["lib"]
optimizer = true
optimizer_runs = 0
evm_version = "prague"
block_gas_limit = 30000000000
via_ir = true

fs_permissions = [{ access = "read", path = "./script/offchain/output/" }]


# 6321: Unnamed return variable can remain unassigned. Add an explicit return with value to all non-reverting code paths or name the variable.
ignored_error_codes = [3860, 5574, 5667, 6321]

[etherscan]
base-sepolia = { key = "${BASE_SEPOLIA_ETHERSCAN_API_KEY}", url = "https://api-sepolia.basescan.org/api" }

[rpc_endpoints]
base = "${BASE_RPC_URL}"
base_sepolia = "${BASE_SEPOLIA_RPC_URL}"
mainnet = "${MAINNET_RPC_URL}"

[fmt]
single_line_statement_blocks = "multi"
multiline_func_header = "params_first"
sort_imports = true
line_length = 120
tab_width = 4
int_types = "short"
quote_style = "single"
number_underscore = "preserve"
wrap_comments = true

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
